name: CI + CD

env:
  MAJOR: 1
  MINOR: 1

on:

  push:
    
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build components
        run: |
          mkdir output && cd $_
          echo "Build artifacts for $MAJOR.$MINOR.$GITHUB_RUN_NUMBER" >> $MAJOR.$MINOR.$GITHUB_RUN_NUMBER.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: |
            output
          

  DeployDev:
    name: Deploy to Dev 
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: 'http://dev.myapp.com'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: deploy/artifact
      - name: Deploy
        run: |
          cat deploy/artifact/$MAJOR.$MINOR.$GITHUB_RUN_NUMBER.txt

  DeployStaging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: 'http://test.myapp.com'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: deploy/artifact
      - name: Deploy
        run: |
          cat deploy/artifact/$MAJOR.$MINOR.$GITHUB_RUN_NUMBER.txt

  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: 'http://www.myapp.com'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: deploy/artifact
      - name: Deploy
        run: |
          cat deploy/artifact/$MAJOR.$MINOR.$GITHUB_RUN_NUMBER.txt