name: Deploy

on:

  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  
  DeployDev:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: 'http://dev.myapp.com'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: deploy/artifact
      - name: Deploy
        run: |
          cat deploy/artifact/$MAJOR.$MINOR.$GITHUB_RUN_NUMBER.txt

  DeployStaging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: 'http://test.myapp.com'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: deploy/artifact
      - name: Deploy
        run: |
          cat deploy/artifact/$MAJOR.$MINOR.$GITHUB_RUN_NUMBER.txt

  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: 'http://www.myapp.com'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: deploy/artifact
      - name: Deploy
        run: |
          cat deploy/artifact/$MAJOR.$MINOR.$GITHUB_RUN_NUMBER.txt