name: Deploy to Staging and Prod

on:

  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  DeployStaging:
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: 'http://test.myapp.com'
    steps:
      - uses: blablacar/action-download-last-artifact@master
        with:
          name: build-artifact
          # Optional, directory where to extract artifact
          path: deploy/artifact
      - name: Deploy
        run: |
          cd deploy/artifact
          deployment_file=(*)
          cat "$deployment_file"

  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: 'http://www.myapp.com'
    steps:
      - uses: blablacar/action-download-last-artifact@master
        with:
          name: build-artifact
          # Optional, directory where to extract artifact
          path: deploy/artifact
      - name: Deploy
        run: |
          cd deploy/artifact
          deployment_file=(*)
          cat "$deployment_file"