name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: deploy
        run: |
          echo "Deployment completed"